# Docker compose file used during development to launch supporting application infrastructure and debugging tools

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./docker/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    environment:
      ES_JAVA_OPTS: -XX:UseAVX=2 -Xms1g -Xmx1g
      ELASTIC_PASSWORD: elastic@123
    ulimits:
      memlock:
        hard: -1
        soft: -1
    networks:
      - webnet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./docker/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - '5601:5601'
    networks:
      - webnet
    depends_on:
      - elasticsearch

networks:
  webnet:

volumes:
  elasticsearch:
